#Hello, thank you very much for downloading the plugin, this is my first
#plugin coded by me, Anyelo120 if you have any suggestions or report any
#bugs you can join our discord: https://discord.gg/tny6zvh4EC

#Modifies the name of the plugin you point to.
plugin_name: '&8[&6&lRoleplay&b&lMessages&8] '

#Modifies the permissions of the plugin you point to
permission:
  Admin_permission: rm.admin
  Amazon_permission: rm.amazon
  Anon_permission: rm.anon
  Emergency_permission: rm.emergency
  Instagram_permission: rm.instagram
  Tinder_permission: rm.tinder
  Twt_permission: rm.twt
  Wsp_permission: rm.wsp
  Rm_Permission: rm.reload
  Ooc_Permission: rm.ooc
  Environment_Permission: rm.environment

#Modify the messages as you wish.
Messages:
  Wsp: '&8[&a&lWSP&8] '
  Tinder: '&7[&d&lTINDER&7] '
  Admin: '&6[&e&lADMIN&6] '
  Twt: '&b&lTWT '
  Instagram: '&7[&6&lINSTAGRAM&7] '
  Anon: '&7[&c&lANON &7] &8>> '
  Emergency: '&c[&4&l911&c] &f+> '
  Amazon: '&8[&c&lAMAZON&8] '
  Ooc: '&7#&8OOC '
  Environment: '>&6&l[&eEnvironment&6&l]< | '
  
#Modifies the plugin's messages.
Lang:
  Error_alert: '¡&cFailed to send, you must write something to send or have permissions to do this.!'
  Console_alert: '&cThis command cannot be executed from the console'
  No_online: '&c¡Player not online!'
  Command_no_exist: '&cThat command was not found'