main: anyelo.central.plugin.Main
version: 2.1.1-ULTIMATED
name: RoleplayMessages
author: Anyelo
description: this plugin adds new messages to use for your server roleplay

commands:
  rm:
    description: general command to move between the interface
  wsp:
    description: WSP command, message private
  instagram:
    description: Instagram command, message global
  twt:
    description: Twt command, message global
  911:
    description: 911 command, message global
  anon:
    description: Anon command, message global
  amazon:
    description: amazon command, message global
  tinder:
    description: tinder command, message global
  admin:
    description: admin command, message global
  ooc:
    description: ooc command, message global
  ent:
    description: ent command, message global
  taxi:
    description: Taxi command, message global